[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_site_packages = true

[[tool.mypy.overrides]]
module = [
    "{{ cookiecutter.project_slug }}.*.migrations.*",
    "{{ cookiecutter.project_slug }}.*.models.*",
]
ignore_errors = true

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true

[tool.black]
line-length = 120
target-version = ['py39']

[tool.bandit]
target = "{{ cookiecutter.project_slug }}"
